apiVersion: apps/v1
kind: Deployment
metadata:
  name: applify-frontend-deployment
  labels:
    name: applify-frontend-deployment
    app: applify
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp-pod
      app: applify
  template:
    metadata:
      name: webapp-pod
      labels:
        name: webapp-pod
        app: applify
    spec:
        containers:
        - name: frontend-container
          image: mastipatel17/applify-frontend:latest
          ports:
          - containerPort: 80

        - name: backend-container
          image: mastipatel17/applify-backend:latest
          ports:
          - containerPort: 8080  